apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: svc-one-apps
  name: demo-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: demoapp
  project: svc-one
  source:
    path: charts/myapp
    repoURL: https://github.com/lacj01-od/argocd_demo
    targetRevision: testapp
    chart: demoapp
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true