apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: svc-one-apps
  name: demo-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: demoapp
  project: svc-one
  source:
    path: charts/myapp
    repoURL: https://github.com/lacj01-od/argocd_demo.git
    targetRevision: testapp_minimal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
