apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: svc-one
  namespace: argo-cd
spec:
  namespaceResourceWhitelist:
    - group: core.oam.dev
      kind: Application
  destinations:
    - namespace: 'demoapp'
      server: 'in-cluster'
  sourceRepos:
    - '*'
  sourceNamespaces:
    - svc-one-apps
