apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: allapps
  namespace: sysproject-apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: sysproject-apps
  project: sysproject
  source:
    path: allapps/
    repoURL: https://github.com/lacj01-od/argocd_demo
    targetRevision: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true