apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: sysproject-apps
  name: kubevela
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: vela-system
  project: sysproject
  source:
    path: charts/vela
    repoURL: https://github.com/lacj01-od/argocd_demo
    targetRevision: bootstrap
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: apiregistration.k8s.io
      kind: APIService
      jsonPointers:
        - /spec/insecureSkipTLSVerify