apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: sysproject-apps
  name: kubevela
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: vela-system
  project: sysproject
  source:
    path: charts/vela
    repoURL: https://github.com/lacj01-od/argocd_demo
    targetRevision: bootstrap
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: apiregistration.k8s.io
      kind: APIService
      # Added this as for some reason the only value is false
      # And when it's set to false, it will be removed as it's the only value.
      # In any case, the helm chart set's this to false and then it disapears
      # as false is the default value.
      jsonPointers:
        - /spec/insecureSkipTLSVerify