argo-cd:
  dex:
    enabled: false
  server:
    extraArgs:
      - "--insecure"
      - "--application-namespaces"
      - "*-apps"
    config:
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
  controller:
    extraArgs:
      - "--application-namespaces"
      - "*-apps"
