apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platformeng
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: platformeng
  project: default
  source:
    path: charts/platformeng
    repoURL: https://github.com/lacj01-od/argocd_demo
    targetRevision: plateng
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true